services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: cyannobat
      POSTGRES_USER: cyannobat
      POSTGRES_PASSWORD: cyannopass
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U cyannobat"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PAYLOAD_DB_PUSH=true
      - PAYLOAD_RUN_MIGRATIONS=false

volumes:
  pg_data:
  redis_data:
