import animate from 'tailwindcss-animate';

/** @type {import('tailwindcss').Config} */
const config = {
  darkMode: ['class', '[data-theme="dark"]'],
  content: ['./src/**/*.{js,ts,jsx,tsx}', './styles/**/*.{css,scss}'],
  theme: {
    extend: {
      colors: {
        background: 'var(--color-bg)',
        foreground: 'var(--color-fg)',
        muted: {
          DEFAULT: 'var(--color-muted)',
          foreground: 'var(--color-muted-foreground)',
        },
        card: {
          DEFAULT: 'var(--color-card)',
          92: 'var(--color-card-92)',
          90: 'var(--color-card-90)',
          88: 'var(--color-card-88)',
          86: 'var(--color-card-86)',
          85: 'var(--color-card-85)',
          82: 'var(--color-card-82)',
          78: 'var(--color-card-78)',
          76: 'var(--color-card-76)',
          75: 'var(--color-card-75)',
          74: 'var(--color-card-74)',
          72: 'var(--color-card-72)',
          70: 'var(--color-card-70)',
          68: 'var(--color-card-68)',
          65: 'var(--color-card-65)',
          64: 'var(--color-card-64)',
          62: 'var(--color-card-62)',
          60: 'var(--color-card-60)',
          58: 'var(--color-card-58)',
          50: 'var(--color-card-50)',
          12: 'var(--color-card-12)',
        },
        border: {
          DEFAULT: 'var(--color-border)',
          45: 'var(--color-border-45)',
          80: 'var(--color-border-80)',
          85: 'var(--color-border-85)',
        },
        accent: {
          DEFAULT: 'var(--color-accent)',
          12: 'var(--color-accent-12)',
          16: 'var(--color-accent-16)',
          18: 'var(--color-accent-18)',
          20: 'var(--color-accent-20)',
          22: 'var(--color-accent-22)',
          24: 'var(--color-accent-24)',
          28: 'var(--color-accent-28)',
          30: 'var(--color-accent-30)',
          32: 'var(--color-accent-32)',
          35: 'var(--color-accent-35)',
          36: 'var(--color-accent-36)',
          38: 'var(--color-accent-38)',
          40: 'var(--color-accent-40)',
          42: 'var(--color-accent-42)',
          45: 'var(--color-accent-45)',
          50: 'var(--color-accent-50)',
          55: 'var(--color-accent-55)',
          foreground: 'var(--color-fg)',
        },
        'accent-strong': {
          DEFAULT: 'var(--color-accent-strong)',
          12: 'var(--color-accent-strong-12)',
          14: 'var(--color-accent-strong-14)',
          16: 'var(--color-accent-strong-16)',
          18: 'var(--color-accent-strong-18)',
          20: 'var(--color-accent-strong-20)',
          22: 'var(--color-accent-strong-22)',
          24: 'var(--color-accent-strong-24)',
          25: 'var(--color-accent-strong-25)',
          26: 'var(--color-accent-strong-26)',
          28: 'var(--color-accent-strong-28)',
          32: 'var(--color-accent-strong-32)',
          40: 'var(--color-accent-strong-40)',
          45: 'var(--color-accent-strong-45)',
          50: 'var(--color-accent-strong-50)',
        },
        white: {
          DEFAULT: 'var(--color-white)',
          16: 'var(--color-white-16)',
          18: 'var(--color-white-18)',
          24: 'var(--color-white-24)',
          25: 'var(--color-white-25)',
          32: 'var(--color-white-32)',
          40: 'var(--color-white-40)',
          45: 'var(--color-white-45)',
          50: 'var(--color-white-50)',
          55: 'var(--color-white-55)',
          60: 'var(--color-white-60)',
          62: 'var(--color-white-62)',
          65: 'var(--color-white-65)',
          68: 'var(--color-white-68)',
          70: 'var(--color-white-70)',
          75: 'var(--color-white-75)',
          78: 'var(--color-white-78)',
          82: 'var(--color-white-82)',
          88: 'var(--color-white-88)',
          90: 'var(--color-white-90)',
          95: 'var(--color-white-95)',
        },
        navy: {
          DEFAULT: 'var(--color-navy)',
          12: 'var(--color-navy-12)',
          18: 'var(--color-navy-18)',
          28: 'var(--color-navy-28)',
          30: 'var(--color-navy-30)',
          32: 'var(--color-navy-32)',
          35: 'var(--color-navy-35)',
          38: 'var(--color-navy-38)',
          42: 'var(--color-navy-42)',
          45: 'var(--color-navy-45)',
          55: 'var(--color-navy-55)',
        },
        midnight: {
          DEFAULT: 'var(--color-midnight)',
          60: 'var(--color-midnight-60)',
          65: 'var(--color-midnight-65)',
          68: 'var(--color-midnight-68)',
          70: 'var(--color-midnight-70)',
          72: 'var(--color-midnight-72)',
          78: 'var(--color-midnight-78)',
          82: 'var(--color-midnight-82)',
        },
        ring: {
          DEFAULT: 'var(--color-ring)',
          85: 'var(--color-ring-85)',
        },
      },
      borderRadius: {
        '3xl': '1.75rem',
        '4xl': '2rem',
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      boxShadow: {
        glass: '0 30px 80px -35px #0f172a73, inset 0 1px 0 var(--color-white-45)',
        'btn-primary': '0 20px 48px -24px var(--color-accent-45), 0 10px 18px -16px var(--color-navy-28)',
        'btn-primary-hover': '0 28px 60px -24px var(--color-accent-55), 0 16px 24px -18px #2a4a7d57',
        'btn-primary-dark': '0 24px 56px -26px var(--color-accent-55), 0 12px 28px -18px var(--color-midnight-60)',
        'btn-primary-dark-hover': '0 32px 68px -28px #78beff99, 0 18px 36px -20px var(--color-midnight-65)',
        'btn-secondary': '0 16px 36px -24px var(--color-navy-28), inset 0 1px 0 var(--color-white-55)',
        'btn-secondary-hover': '0 20px 44px -26px var(--color-accent-32), inset 0 1px 0 var(--color-white-60)',
        'btn-secondary-dark': '0 22px 48px -28px var(--color-midnight-72), inset 0 1px 0 var(--color-accent-strong-18)',
        'btn-secondary-dark-hover': '0 30px 58px -30px var(--color-accent-32), inset 0 1px 0 var(--color-accent-strong-22)',
      },
      backdropBlur: {
        glass: '20px',
      },
      fontFamily: {
        vazir: ['var(--font-vazirmatn)', 'sans-serif'],
      },
    },
  },
  plugins: [animate],
};

export default config;
